import { Link } from "react-router-dom";
import { Card, EmptyState } from "../../../components/ui";
import { useAccounts } from "../../accounts/hooks";
import { useLoginLogsQuery } from "../../logs/hooks";
import { useSourcesQuery } from "../../sources/hooks";

const Metric = ({ label, value, detail, alert = false }: { label: string; value: number; detail: string; alert?: boolean }) => <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-caption font-semibold uppercase tracking-wide text-text-muted">{label}</p><p className="mt-2 text-h2 font-semibold text-text-primary">{value}</p></div><span className={`mt-1 h-2.5 w-2.5 rounded-full ${alert ? "bg-danger" : "bg-success"}`} aria-hidden="true" /></div><p className="mt-3 text-small text-text-muted">{detail}</p></Card>;
const ActionLink = ({ to, title, description }: { to: string; title: string; description: string }) => <Link to={to} className="block rounded-lg border border-border bg-surface-raised p-5 shadow-raised hover:bg-surface-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"><p className="font-semibold text-text-primary">{title}</p><p className="mt-2 text-small text-text-muted">{description}</p><p className="mt-4 text-small font-semibold text-accent">Open {title.toLowerCase()} →</p></Link>;

export const SuperAdminDashboardPage = () => {
  const { data: accounts = [] } = useAccounts();
  const { data: sources = [] } = useSourcesQuery();
  const { data: failedLogins } = useLoginLogsQuery({ result: "failure", page: 1, pageSize: 1 });
  const activeAccounts = accounts.filter((account) => account.is_active).length;
  const inactiveSources = sources.filter((source) => !source.is_active).length;
  return <div className="space-y-6"><section className="rounded-lg border border-border bg-surface-raised p-5 sm:p-6"><p className="text-caption font-semibold uppercase tracking-wide text-accent">System administration</p><h2 className="mt-2 text-h3 font-semibold text-text-primary">Super Admin control center</h2><p className="mt-2 max-w-2xl text-small text-text-muted">Live account, source, and login information from the backend.</p></section><section aria-label="System metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active accounts" value={activeAccounts} detail={`${accounts.length - activeAccounts} inactive accounts`} /><Metric label="Sources" value={sources.length} detail={`${inactiveSources} inactive sources`} alert={inactiveSources > 0} /><Metric label="Active sources" value={sources.length - inactiveSources} detail="Sources currently enabled" /><Metric label="Failed logins" value={failedLogins?.total ?? 0} detail="Recorded unsuccessful attempts" alert={(failedLogins?.total ?? 0) > 0} /></section><section><h2 className="mb-4 text-h4 font-semibold text-text-primary">Administration</h2><div className="grid gap-4 md:grid-cols-3"><ActionLink to="/superadmin/accounts" title="Accounts" description="Create, update, activate, or deactivate administrator access." /><ActionLink to="/superadmin/sources" title="Sources" description="Monitor sources and control ingestion availability." /><ActionLink to="/superadmin/logs/login" title="Login logs" description="Review recorded authentication activity." /></div></section><Card><EmptyState title="Audit summary unavailable" description="Sample audit activity was removed. A protected audit-log API is required before privileged changes can be shown here." /></Card></div>;
};
