/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: {
          50: "var(--gray-50)",
          100: "var(--gray-100)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          600: "var(--gray-600)",
          700: "var(--gray-700)",
          800: "var(--gray-800)",
          900: "var(--gray-900)",
        },
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-active": "var(--color-accent-active)",
        surface: "var(--color-surface)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-muted": "var(--color-surface-muted)",
        "text-primary": "var(--color-text-primary)",
        "text-muted": "var(--color-text-muted)",
        "text-inverse": "var(--color-text-inverse)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        danger: "var(--color-danger)",
        "danger-hover": "var(--color-danger-hover)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        "focus-ring": "var(--color-focus-ring)",
        "input-bg": "var(--input-bg)",
        "input-border": "var(--input-border)",
        "input-border-hover": "var(--input-border-hover)",
        "input-border-focus": "var(--input-border-focus)",
        "button-primary-bg": "var(--button-primary-bg)",
        "button-primary-bg-hover": "var(--button-primary-bg-hover)",
        "button-primary-bg-active": "var(--button-primary-bg-active)",
        "button-primary-text": "var(--button-primary-text)",
        "card-bg": "var(--card-bg)",
        "card-border": "var(--card-border)",
      },
      fontFamily: {
        sans: [
          "Noto Sans",
          "Noto Sans Arabic",
          "Segoe UI",
          "Tahoma",
          "Arial",
          "sans-serif",
        ],
      },
      fontSize: {
        caption: ["0.75rem", { lineHeight: "1.45" }],
        small: ["0.875rem", { lineHeight: "1.45" }],
        body: ["1rem", { lineHeight: "1.5" }],
        "body-large": ["1.125rem", { lineHeight: "1.5" }],
        h4: ["1.25rem", { lineHeight: "1.35" }],
        h3: ["1.5625rem", { lineHeight: "1.3" }],
        h2: ["1.9375rem", { lineHeight: "1.2" }],
        h1: ["2.4375rem", { lineHeight: "1.15" }],
        display: ["3.0625rem", { lineHeight: "1.1" }],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
      },
      boxShadow: {
        raised: "var(--shadow-raised)",
        overlay: "var(--shadow-overlay)",
      },
    },
  },
  plugins: [],
}
