"""add incidents and incident details

Revision ID: 20260811_0007
Revises: 20260811_0006
Create Date: 2026-08-11

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260811_0007"
down_revision: Union[str, Sequence[str], None] = "20260811_0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    did_value = postgresql.ENUM("D", "ID", name="did_value", create_type=False)
    did_value.create(op.get_bind(), checkfirst=True)

    def did_column(name: str) -> sa.Column:
        return sa.Column(name, did_value, nullable=True)

    op.create_table(
        "incidents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("raw_message_id", sa.BigInteger(), nullable=True),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("event_month", sa.String(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.Time(), nullable=True),
        sa.Column("khabar", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("moh", sa.String(), nullable=True),
        sa.Column("martyrs", sa.Text(), nullable=True),
        sa.Column("worker_name", sa.String(), nullable=True),
        sa.Column("source_link", sa.Text(), nullable=True),
        sa.Column("source_link_2", sa.Text(), nullable=True),
        sa.Column("total_deaths", sa.Integer(), nullable=True),
        sa.Column("total_injuries", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("injuries", sa.Integer(), nullable=True),
        sa.Column("injuries_extra", sa.Integer(), nullable=True),
        sa.Column("note_extra", sa.Text(), nullable=True),
        sa.Column("exact_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("incident_key", sa.String(), nullable=True),
        sa.Column(
            "duplicate_flag",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["conditions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["village_id"], ["villages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_incidents_exact_hash_active",
        "incidents",
        ["exact_hash"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    op.create_table(
        "incident_details",
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("male_d", sa.Integer(), nullable=True),
        sa.Column("male_i", sa.Integer(), nullable=True),
        sa.Column("female_d", sa.Integer(), nullable=True),
        sa.Column("female_i", sa.Integer(), nullable=True),
        sa.Column("children_d", sa.Integer(), nullable=True),
        sa.Column("children_i", sa.Integer(), nullable=True),
        sa.Column("obs_duties", sa.Boolean(), nullable=True),
        sa.Column("isf_gs", sa.Boolean(), nullable=True),
        sa.Column("fire", sa.Boolean(), nullable=True),
        sa.Column("arrested", sa.Boolean(), nullable=True),
        sa.Column("lib_y_n", sa.String(), nullable=True),
        sa.Column("la", sa.Boolean(), nullable=True),
        did_column("la_did"),
        sa.Column("la_bldg", sa.Boolean(), nullable=True),
        sa.Column("la_v", sa.Boolean(), nullable=True),
        sa.Column("lam_d", sa.Integer(), nullable=True),
        sa.Column("lam_i", sa.Integer(), nullable=True),
        sa.Column("laf_d", sa.Integer(), nullable=True),
        sa.Column("laf_i", sa.Integer(), nullable=True),
        sa.Column("la_td", sa.Integer(), nullable=True),
        sa.Column("la_ti", sa.Integer(), nullable=True),
        sa.Column("unifil", sa.Boolean(), nullable=True),
        did_column("un_did"),
        sa.Column("un_bldg", sa.Boolean(), nullable=True),
        sa.Column("un_v", sa.Boolean(), nullable=True),
        sa.Column("unm_d", sa.Integer(), nullable=True),
        sa.Column("unm_i", sa.Integer(), nullable=True),
        sa.Column("unf_d", sa.Integer(), nullable=True),
        sa.Column("unf_i", sa.Integer(), nullable=True),
        sa.Column("un_td", sa.Integer(), nullable=True),
        sa.Column("un_ti", sa.Integer(), nullable=True),
        sa.Column("muni", sa.Boolean(), nullable=True),
        did_column("muni_did"),
        sa.Column("muni_bldg", sa.Boolean(), nullable=True),
        sa.Column("muni_empl", sa.Boolean(), nullable=True),
        sa.Column("munim_d", sa.Integer(), nullable=True),
        sa.Column("munim_i", sa.Integer(), nullable=True),
        sa.Column("munif_d", sa.Integer(), nullable=True),
        sa.Column("munif_i", sa.Integer(), nullable=True),
        sa.Column("muni_td", sa.Integer(), nullable=True),
        sa.Column("muni_ti", sa.Integer(), nullable=True),
        sa.Column("school", sa.Boolean(), nullable=True),
        did_column("sch_did"),
        sa.Column("school_name", sa.String(), nullable=True),
        sa.Column("school_damage_level", sa.String(), nullable=True),
        sa.Column("uni", sa.Boolean(), nullable=True),
        did_column("uni_did"),
        sa.Column("uni_name", sa.String(), nullable=True),
        sa.Column("church", sa.Boolean(), nullable=True),
        did_column("chu_did"),
        sa.Column("chu_n", sa.String(), nullable=True),
        sa.Column("mosque", sa.Boolean(), nullable=True),
        did_column("mos_did"),
        sa.Column("mosque_n", sa.String(), nullable=True),
        sa.Column("ceme", sa.Boolean(), nullable=True),
        did_column("ceme_did"),
        sa.Column("ceme_n", sa.String(), nullable=True),
        sa.Column("releg", sa.Boolean(), nullable=True),
        did_column("releg_did"),
        sa.Column("releg_n", sa.String(), nullable=True),
        sa.Column("archeo", sa.Boolean(), nullable=True),
        did_column("arch_did"),
        sa.Column("arch_n", sa.String(), nullable=True),
        sa.Column("hosp", sa.Boolean(), nullable=True),
        did_column("hos_did"),
        sa.Column("hos_status", sa.String(), nullable=True),
        sa.Column("hos_n", sa.String(), nullable=True),
        sa.Column("hos_damage_level", sa.String(), nullable=True),
        sa.Column("nbr_evap", sa.Integer(), nullable=True),
        sa.Column("hosm_d", sa.Integer(), nullable=True),
        sa.Column("hosm_i", sa.Integer(), nullable=True),
        sa.Column("hosf_d", sa.Integer(), nullable=True),
        sa.Column("hosf_i", sa.Integer(), nullable=True),
        sa.Column("hosd", sa.Integer(), nullable=True),
        sa.Column("hosi", sa.Integer(), nullable=True),
        sa.Column("hc", sa.Boolean(), nullable=True),
        sa.Column("hc_rela", sa.String(), nullable=True),
        did_column("hc_did"),
        sa.Column("hc_damage_level", sa.String(), nullable=True),
        sa.Column("hcm_d", sa.Integer(), nullable=True),
        sa.Column("hcm_i", sa.Integer(), nullable=True),
        sa.Column("hcf_d", sa.Integer(), nullable=True),
        sa.Column("hcf_i", sa.Integer(), nullable=True),
        sa.Column("hcd", sa.Integer(), nullable=True),
        sa.Column("hci", sa.Integer(), nullable=True),
        sa.Column("emer", sa.Boolean(), nullable=True),
        sa.Column("e_cars", sa.Boolean(), nullable=True),
        sa.Column("car_nbr", sa.Integer(), nullable=True),
        sa.Column("emer_rela", sa.String(), nullable=True),
        sa.Column("emer_d", sa.Integer(), nullable=True),
        sa.Column("emer_i", sa.Integer(), nullable=True),
        sa.Column("press", sa.Boolean(), nullable=True),
        sa.Column("channel", sa.String(), nullable=True),
        did_column("press_did"),
        sa.Column("pressm_d", sa.Integer(), nullable=True),
        sa.Column("pressm_i", sa.Integer(), nullable=True),
        sa.Column("pressf_d", sa.Integer(), nullable=True),
        sa.Column("pressf_i", sa.Integer(), nullable=True),
        sa.Column("pressd", sa.Integer(), nullable=True),
        sa.Column("pressi", sa.Integer(), nullable=True),
        sa.Column("gov", sa.Boolean(), nullable=True),
        sa.Column("gov_bui", sa.String(), nullable=True),
        sa.Column("gov_n", sa.String(), nullable=True),
        did_column("gb_did"),
        sa.Column("gbm_d", sa.Integer(), nullable=True),
        sa.Column("gbm_i", sa.Integer(), nullable=True),
        sa.Column("gbf_d", sa.Integer(), nullable=True),
        sa.Column("gbf_i", sa.Integer(), nullable=True),
        sa.Column("gbd", sa.Integer(), nullable=True),
        sa.Column("gbi", sa.Integer(), nullable=True),
        sa.Column("road", sa.Boolean(), nullable=True),
        did_column("road_d_id"),
        sa.Column("road_blocked", sa.Boolean(), nullable=True),
        sa.Column("road_name", sa.String(), nullable=True),
        sa.Column("bridge", sa.Boolean(), nullable=True),
        sa.Column("bridge_blocked", sa.Boolean(), nullable=True),
        sa.Column("bridge_name", sa.String(), nullable=True),
        sa.Column("car", sa.Boolean(), nullable=True),
        sa.Column("card", sa.Integer(), nullable=True),
        sa.Column("cari", sa.Integer(), nullable=True),
        sa.Column("carm_d", sa.Integer(), nullable=True),
        sa.Column("carm_i", sa.Integer(), nullable=True),
        sa.Column("carf_d", sa.Integer(), nullable=True),
        sa.Column("carf_i", sa.Integer(), nullable=True),
        sa.Column("carc_d", sa.Integer(), nullable=True),
        sa.Column("carc_i", sa.Integer(), nullable=True),
        sa.Column("moto", sa.Boolean(), nullable=True),
        did_column("moto_did"),
        sa.Column("moto_d", sa.Integer(), nullable=True),
        sa.Column("moto_i", sa.Integer(), nullable=True),
        sa.Column("con_veh", sa.Boolean(), nullable=True),
        sa.Column("con_d", sa.Integer(), nullable=True),
        sa.Column("con_i", sa.Integer(), nullable=True),
        sa.Column("excavator", sa.Boolean(), nullable=True),
        sa.Column("bulldozer", sa.Boolean(), nullable=True),
        sa.Column("camion", sa.Boolean(), nullable=True),
        sa.Column("bobcat", sa.Boolean(), nullable=True),
        sa.Column("tracteur", sa.Boolean(), nullable=True),
        sa.Column("total_con", sa.Integer(), nullable=True),
        sa.Column("crossing", sa.Boolean(), nullable=True),
        sa.Column("litani", sa.Boolean(), nullable=True),
        sa.Column("zahrani", sa.Boolean(), nullable=True),
        sa.Column("drone_f", sa.Boolean(), nullable=True),
        sa.Column("water", sa.Boolean(), nullable=True),
        did_column("water_did"),
        sa.Column("water_type", sa.String(), nullable=True),
        sa.Column("electric", sa.Boolean(), nullable=True),
        did_column("electric_did"),
        sa.Column("electric_type", sa.String(), nullable=True),
        sa.Column("olives_trees_d", sa.Integer(), nullable=True),
        sa.Column("mjnoub", sa.Boolean(), nullable=True),
        did_column("mj_did"),
        sa.Column("other", sa.Boolean(), nullable=True),
        did_column("other_did"),
        sa.Column("other_type", sa.String(), nullable=True),
        sa.Column("other_d", sa.Integer(), nullable=True),
        sa.Column("other_i", sa.Integer(), nullable=True),
        sa.Column("no_warning", sa.Boolean(), nullable=True),
        sa.Column("warning", sa.Boolean(), nullable=True),
        sa.Column("genocide", sa.Boolean(), nullable=True),
        sa.Column("building", sa.Boolean(), nullable=True),
        sa.Column("apart", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_id"),
    )


def downgrade() -> None:
    op.drop_table("incident_details")
    op.drop_index("uq_incidents_exact_hash_active", table_name="incidents")
    op.drop_table("incidents")

    did_value = postgresql.ENUM(name="did_value")
    did_value.drop(op.get_bind(), checkfirst=True)
